server:
  port: ${APPLICATION_PORT:8081}
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never

spring:
  application:
    name: helpdesk
  flyway:
    enable: true
    baseline-on-migrate: false
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

helpdesk:
  attachments-folder: ${ATTACHMENTS_FOLDER}


secret:
  jwt: 9I2Vy3MZnpF/BeSuzemBktVFa12mZCRGDkmp0IH5iIE=