
INSERT INTO USUARIO (ID, EMAIL, LOGIN, NOME , SENHA, SITUACAO) VALUES (1, 'antonio@gmail.com', 'antonio', 'Antonio', '123456', 'ATIVO');
INSERT INTO USUARIO (ID, EMAIL, LOGIN, NOME , SENHA, SITUACAO) VALUES (2, 'antonio1@gmail.com', 'antonio1', 'Antonio1', '1234567', 'INATIVO');
INSERT INTO USUARIO (ID, EMAIL, LOGIN, NOME , SENHA, SITUACAO) VALUES (3, 'antonio2@gmail.com', 'antonio2', 'Antonio2', '1234568', 'PENDENTE');


ALTER SEQUENCE USUARIO_ID_SEQ RESTART WITH 4;

INSERT INTO PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO PERFIL (ID, DESCRICAO) VALUES (3, 'cliente');

ALTER SEQUENCE PERFIL_SEQ RESTART WITH 4;


INSERT INTO RECURSO(ID, NOME, CHAVE) VALUES (1, 'Tela Usuario', 'usuario');
INSERT INTO RECURSO(ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO RECURSO(ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE RECURSO_ID_SEQ RESTART WITH 4;
